# Generated by Django 4.1.11 on 2023-09-25 08:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=datetime.datetime(2023, 9, 25, 13, 16, 28, 843137))),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=244, null=True)),
                ('description', models.TextField(default='null', null=True)),
                ('type', models.CharField(choices=[('general', 'general'), ('expense', 'expense'), ('profit', 'profit')], max_length=244, null=True)),
                ('amount', models.CharField(default=0, max_length=244, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=datetime.datetime(2023, 9, 25, 13, 16, 28, 843137))),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('profile_picture', models.ImageField(null=True, upload_to='person/')),
                ('first_name', models.CharField(max_length=244, null=True)),
                ('last_name', models.CharField(max_length=244, null=True)),
                ('email', models.CharField(max_length=244, null=True)),
                ('mobile', models.CharField(max_length=244, null=True)),
                ('address', models.CharField(max_length=244, null=True)),
                ('city', models.CharField(max_length=144, null=True)),
                ('salary', models.CharField(default=0, max_length=244, null=True)),
                ('designation', models.CharField(max_length=244, null=True)),
                ('type', models.CharField(choices=[('employee', 'employee'), ('client', 'client')], max_length=244, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=datetime.datetime(2023, 9, 25, 13, 16, 28, 843137))),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=244, null=True)),
                ('description', models.TextField()),
                ('duration_start', models.DateField(null=True)),
                ('duration_end', models.DateField(null=True)),
                ('amount', models.CharField(max_length=244, null=True)),
                ('clients', models.ManyToManyField(related_name='projects_as_client', to='core.person')),
                ('employees', models.ManyToManyField(related_name='projects_as_employee', to='core.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=datetime.datetime(2023, 9, 25, 13, 16, 28, 843137))),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=244, null=True)),
                ('description', models.TextField(null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], max_length=100, null=True)),
                ('assigned_to', models.ManyToManyField(to='core.person')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalaryInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=datetime.datetime(2023, 9, 25, 13, 16, 28, 843137))),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=244, null=True)),
                ('amount', models.CharField(max_length=244, null=True)),
                ('status', models.CharField(choices=[('due', 'due'), ('paid', 'paid')], max_length=244, null=True)),
                ('previous_dues', models.CharField(default='0', max_length=244, null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=datetime.datetime(2023, 9, 25, 13, 16, 28, 843137))),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=244, null=True)),
                ('amount', models.CharField(max_length=244, null=True)),
                ('status', models.CharField(choices=[('due', 'due'), ('paid', 'paid')], max_length=244, null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=datetime.datetime(2023, 9, 25, 13, 16, 28, 843137))),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('present', 'present'), ('absent', 'absent'), ('leave', 'leave')], max_length=144, null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.person')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
