# Generated by Django 4.2.2 on 2023-06-27 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salaryinvoice',
            old_name='employee',
            new_name='person',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date_created',
            field=models.DateTimeField(default='2023-06-27 21:38:07'),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_created',
            field=models.DateTimeField(default='2023-06-27 21:38:07'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_created',
            field=models.DateTimeField(default='2023-06-27 21:38:07'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_created',
            field=models.DateTimeField(default='2023-06-27 21:38:07'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_created',
            field=models.DateTimeField(default='2023-06-27 21:38:07'),
        ),
        migrations.AlterField(
            model_name='projectinvoice',
            name='date_created',
            field=models.DateTimeField(default='2023-06-27 21:38:07'),
        ),
        migrations.AlterField(
            model_name='salaryinvoice',
            name='date_created',
            field=models.DateTimeField(default='2023-06-27 21:38:07'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_created',
            field=models.DateTimeField(default='2023-06-27 21:38:07'),
        ),
    ]
