# Generated by Django 4.1.11 on 2023-09-28 11:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 28, 16, 50, 51, 507952)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 28, 16, 50, 51, 507952)),
        ),
        migrations.AlterField(
            model_name='person',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 28, 16, 50, 51, 507952)),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 28, 16, 50, 51, 507952)),
        ),
        migrations.AlterField(
            model_name='projectinvoice',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 28, 16, 50, 51, 507952)),
        ),
        migrations.AlterField(
            model_name='salaryinvoice',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 28, 16, 50, 51, 507952)),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 28, 16, 50, 51, 507952)),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=datetime.datetime(2023, 9, 28, 16, 50, 51, 507952))),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=244, null=True)),
                ('description', models.TextField(null=True)),
                ('status', models.CharField(choices=[('open', 'open'), ('closed', 'closed')], default='open', max_length=244, null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
