# Generated by Django 4.2.2 on 2023-06-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_employee_salaryinvoice_person_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salaryinvoice',
            name='person',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date_created',
            field=models.DateTimeField(default='2023-06-27 21:51:45'),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_created',
            field=models.DateTimeField(default='2023-06-27 21:51:45'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_created',
            field=models.DateTimeField(default='2023-06-27 21:51:45'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_created',
            field=models.DateTimeField(default='2023-06-27 21:51:45'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_created',
            field=models.DateTimeField(default='2023-06-27 21:51:45'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_created',
            field=models.DateTimeField(default='2023-06-27 21:51:45'),
        ),
        migrations.DeleteModel(
            name='ProjectInvoice',
        ),
        migrations.DeleteModel(
            name='SalaryInvoice',
        ),
    ]
