# Generated by Django 4.2.2 on 2023-09-23 15:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_salaryinvoice_previous_dues_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.CharField(default=0, max_length=244, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 23, 20, 45, 3, 347850)),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 23, 20, 45, 3, 347850)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 23, 20, 45, 3, 347850)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 23, 20, 45, 3, 347850)),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 23, 20, 45, 3, 347850)),
        ),
        migrations.AlterField(
            model_name='projectinvoice',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 23, 20, 45, 3, 347850)),
        ),
        migrations.AlterField(
            model_name='salaryinvoice',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 23, 20, 45, 3, 347850)),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 23, 20, 45, 3, 347850)),
        ),
    ]
