# Generated by Django 4.1.11 on 2023-09-25 08:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=datetime.datetime(2023, 9, 25, 13, 16, 28, 843137))),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=144, null=True)),
                ('description', models.TextField(null=True)),
                ('type', models.CharField(choices=[('private', 'private'), ('public', 'public')], max_length=144, null=True)),
                ('members', models.ManyToManyField(to='core.person')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=datetime.datetime(2023, 9, 25, 13, 16, 28, 843137))),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(null=True)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chats.room')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.person')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
